type User {
  # email row exists in table but is visible only to the user himself
  # email: String
  id: Int!
  name: String!
  picture: String
}

type UserAuth {
  email: String!
  password: String!
  name: String!
  picture: String
}

type JWT {
  expire_at: String
  token: String
}

input LoginInput {
  email: String!
  password: String!
}

input UserUpdateInput {
  email: String
  password: String
  picture: String
  name: String
}

type Mutation {
  updateUser(id: Int!, input: UserUpdateInput!): User
  deleteUser(id: Int!): Boolean
}

type Query {
  user(id: Int!): User
  users: [User]
  login(input: LoginInput!): JWT
}
