scalar ObjectId

type User {
  _id: ObjectId!
  name: String!
}


type Mutation {
    hello_world_mut: String
}

scalar ObjectId

type Query {
  user(_id: ObjectId!): User
  getUsers: [User]
  hello_world: String
}
