type User {
  email: String
  password: String
  id: Int!
  name: String!
  picture: String
}

type JWT {
  expire_at: String
  token: String
}

input LoginInput {
  email: String!
  password: String!
}

input UserUpdateInput {
  email: String
  password: String
  picture: String
  name: String
}

input UserFilterInput {
  name: String
}

input UserCreateInput {
  email: String!
  password: String!
  picture: String
  name: String!
}

type Mutation {
  updateUser(id: Int!, input: UserUpdateInput!): User
  createUser(input: UserCreateInput!): User
  deleteUser(id: Int!): Boolean
}

type Query {
  user(id: Int!): User
  users(limit: Int, filter: UserFilterInput): [User]
  login(input: LoginInput!): JWT
}
