name: Check script

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [22.x]
=======
        node-version: [20.x]
>>>>>>> 0cff83f (:tada: :hammer: Recoil setup + config fixes + github actions added)

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
<<<<<<< HEAD
      run: pnpm install --no-frozen-lockfile

    - run: pnpm typescript
    - run: pnpm eslint
    - run: pnpm build:client
=======
      run: pnpm install

    - run: pnpm run typescript
    - run: pnpm run eslint
    - run: pnpm run build:client
>>>>>>> 0cff83f (:tada: :hammer: Recoil setup + config fixes + github actions added)
